# Generated by Django 5.2.3 on 2025-06-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='Indonesia', max_length=50),
            preserve_default=False,
        ),
    ]
